algoritmo "migossss gay dms slc"

var

   amigos_catalogados: inteiro

inicio


    escreva("Por favor digite a quantidade de amigos catalogados: ")
    leia(amigos_catalogados)
    escreval("")

    se amigos_catalogados < 5 entao
       escreval("Voce e uma  pessoa tranquila")
    senao
       se amigos_catalogados = 5 entao
           escreval("voce e uma pessoa normal")
       senao
           escreval("TU TA ANIMADO")
       fimse
    fimse

fimalgoritmo