algoritmo "passagem"

var

   turmas_engenharia_2e3_perido : inteiro
   
inicio

   turmas_engenharia_2e3_perido <- 23
   
   se turmas_engenharia_2e3_perido > 30 entao
      escreval("Voces vao ganha uma passagem para Cancum!")
   senao
      se turmas_engenharia_2e3_perido = 30 entao
         escreval("Voces ganharao uma passagem para Fortaleza!")
      senao
         escreval("Voces ganharao uma passagem para caldas novas!")
      fimse
   fimse

   
   
fimalgoritmo

